### ISSUE TITLE
Question 4 of the project

### ISSUE THREAD

**Issue by lalitkumarchauhan** [Gunnvant/sql_for_datascience#1]
The **rating** column in film table is having different ratings but in the **question 4** you have asked about ratings between **2 and 3** or ratings having **4+** value. 

Kindly check the attached one sample from film table.

> Am i missing something?

I have tried the below one for the same question but didn't get a meaningful answer

`SELECT count(film_id), rating FROM film WHERE (rating BETWEEN 2 AND 3) or (rating > 4) GROUP by rating;`

[Page_1_Sample.pdf](https://github.com/Gunnvant/sql_for_datascience/files/10934715/Page_1_Sample.pdf)

**Comment by Gunnvant** [comment]
This seems to be a typo. We will fix it. For the time being consider G, PG,
PG-13, R, or NC-17 rated as 1-5, starting from G to NC-17. Use a case
statement to convert categorical ratings to. numeric.

**Comment by Gunnvant** [comment]
I have changed the problem 4 accordingly. Closing the issue here
